#ifndef WIFI_JOIN_STAGE_H
#define WIFI_JOIN_STAGE_H

enum {
    STAGE_NONE, STAGE_RECONFIGURE, STAGE_LIST, STAGE_SELECT, STAGE_ASSOC,
    STAGE_ADDRESS, STAGE_ENABLE, STAGE_RESTORE, STAGE_ROLLBACK_RECONFIGURE,
    STAGE_ROLLBACK_LIST, STAGE_ROLLBACK_SELECT, STAGE_ROLLBACK_ENABLE,
};

#endif
